# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPAN-Search-Lite
version:      0.76
installdirs:  site
license:      perl
abstract:     set up and maintain a searchable CPAN database
authored_by:
    - Randy Kobes <r.kobes@uwinnipeg.ca>
requires:
    AI::Categorizer:               0
    Archive::Tar:                  1.08
    Archive::Zip:                  1.09
    Config::IniFiles:              0
    CPAN::DistnameInfo:            0
    DBD::mysql:                    0
    File::Spec:                    0
    File::Temp:                    0
    HTML::TextToHTML:              0
    IO::Zlib:                      0
    Lingua::Stem:                  0
    Lingua::StopWords:             0
    Locale::Country:               0
    LWP:                           0
    Perl::Tidy:                    0
    Pod::Select:                   0
    YAML:                          0
    SOAP::Lite:                    0
    XML::SAX::ExpatXS:             0
    Pod::Xhtml:                    0
    Apache2::SOAP:                 0
distribution_type: module
no_index:
    file:
        - Apache2/t/lib/TestCSL.pm
        - Apache2/t/lib/TestCSL/search.pm
        - Apache2/t/response/TestCSL/lang.pm
        - par/cpan/lib/CPAN/Util.pm
        - par/ppm/lib/PPM/Reps.pm
provides:
  Apache2::CPAN::Query:
    file: Apache2/Apache2/CPAN/Query.pm
    version: 0.76
  Apache2::CPAN::Search:
    file: Apache2/Apache2/CPAN/Search.pm
    version: 0.76
  Apache2::CPAN::SOAP:
    file: Apache2/Apache2/CPAN/SOAP.pm
    version: 0.76
  Apache2::DocServer:
    file: Apache2/Apache2/DocServer.pm
    version: 0.76
  CPAN::Search::Lite:
    file: lib/CPAN/Search/Lite.pm
    version: 0.76
  CPAN::Search::Lite::Extract:
    file: lib/CPAN/Search/Lite/Extract.pm
    version: 0.76
  CPAN::Search::Lite::HTML:
    file: lib/CPAN/Search/Lite/HTML.pm
    version: 0.76
  CPAN::Search::Lite::Index:
    file: lib/CPAN/Search/Lite/Index.pm
    version: 0.76
  CPAN::Search::Lite::Info:
    file: lib/CPAN/Search/Lite/Info.pm
    version: 0.76
  CPAN::Search::Lite::Lang:
    file: lib/CPAN/Search/Lite/Lang.pm
    version: 0.76
  CPAN::Search::Lite::Populate:
    file: lib/CPAN/Search/Lite/Populate.pm
    version: 0.76
  CPAN::Search::Lite::PPM:
    file: lib/CPAN/Search/Lite/PPM.pm
    version: 0.76
  CPAN::Search::Lite::Query:
    file: lib/CPAN/Search/Lite/Query.pm
    version: 0.76
  CPAN::Search::Lite::State:
    file: lib/CPAN/Search/Lite/State.pm
    version: 0.76
  CPAN::Search::Lite::Util:
    file: lib/CPAN/Search/Lite/Util.pm
    version: 0.76
  CPAN::Search::Lite::Lang::de:
    file: lib/CPAN/Search/Lite/Lang/de.pm
    version: 0.76
  CPAN::Search::Lite::Lang::en:
    file: lib/CPAN/Search/Lite/Lang/en.pm
    version: 0.76
  CPAN::Search::Lite::Lang::es:
    file: lib/CPAN/Search/Lite/Lang/es.pm
    version: 0.76
  CPAN::Search::Lite::Lang::fr:
    file: lib/CPAN/Search/Lite/Lang/fr.pm
    version: 0.76
  CPAN::Search::Lite::Lang::it:
    file: lib/CPAN/Search/Lite/Lang/it.pm
    version: 0.76
  CPAN::Search::Lite::Lang::pt:
    file: lib/CPAN/Search/Lite/Lang/pt.pm
    version: 0.76
  CPAN::Search::Lite::DBI:
    file: lib/CPAN/Search/Lite/DBI.pm
    version: 0.76
  CPAN::Search::Lite::DBI::Query:
    file: lib/CPAN/Search/Lite/DBI/Query.pm
    version: 0.76
  CPAN::Search::Lite::DBI::Index:
    file: lib/CPAN/Search/Lite/DBI/Index.pm
    version: 0.76
generated_by: ExtUtils::MakeMaker version 6.17
